Luo = {
    'Good morning': 'Nang\'o',
    'Good afternoon/evening': 'Irio nade',
    'Sir': 'Jatelo',
    'Madam': 'Jaber',
    'Good': 'Ber',
    'welcome': 'Machiegni',
    'Alright': 'Kamano',
    'Glad to see you': 'Ber neni',
    'Please have a seat': 'Kao kom',
    'Pineapple': 'Mananas',
    'Papaya': 'Apoyo',
    'Bananas': 'Rabolo',
    'Mango': 'Maembe',
    'Introduction': 'Ulrwoko',
    'Try': 'Tem',
    'I am': 'Am',
    'You': 'In',
    'He/She': 'En',
    'My name': 'Nyinga',
    'or': 'kata',
    'They call': 'Gigocho',
    'Woman':'Min',
    'Girl': 'Nyako',
    'Man':'Dichuo',
    'Boy': 'Wuoyi',
    'No problem': 'Onge wach',
    'God':'Nyasaye',
    'My man':'Chuora',
    'My child': 'Nyathina',
    'My boy': 'Wuoda',
    'Young':'Tin',
    'I am done': 'Atieko',
    'Yes':'Eee',
    'No': 'Ooyo',
    'Water': 'Pi',
    'We are done': 'Watieko',
    'Today': 'Kawuono',
    'Amen': 'Amen',
    'Praise God':'Nyasaye ogwedhi',
    'I am studying': 'Asomo',
    'Eating': 'Chiemo',
    'How': 'Nade',
    'There':'Kae',
    'How did you spend the night': 'Inindo nade',
    'Well':'Ber',
    'Thank you':'Erokamano',
    'You also':'Na wewe',
    'Work': 'Tich',
    'I am excited to see you': 'Amore neni',
    'May I come in?':'Adonji',
    'Come in':'Ndonji',
    'Welcome home':'Machiegni ot',
    'I have returned':'Aduogo',
    'I greet you ': 'Amosi',
    'How are you?': 'Idhi nade?',
    'What do you say?': 'Iwacho nang\'o?',
    'What\'s up friend?': 'Ang\'o osiepa',
    'Greet them!': 'Mos gi',
    'Good bye':'Oriti',
    'Soon': 'Machiegni ni',
    'The people at home': 'Ji ot',
    'They are': 'Gin',
    'Home': 'Ot',
    'What':'Ang\'o',
    'People': 'Ji',
    'Any news?':'Wach mora mora',
    'Food':'Chiemo',
        }
