lusoga = {
    'Good morning': 'Wasuze otya',
    'Good afternoon/evening': 'Osibye otya',
    'Sir': 'Ssebo',
    'Madam': 'Nyabo',
    'Good': 'Bulungi',
    'welcome': 'Tusangaire',
    'welcome one': 'Nsangaire',
    'Alright': 'Kale',
    'glad to see you': 'Tusangaire okukubona',
    'Please have a seat': 'Akatebe kako',
    'Pineapple': 'Enanhasi',
    'Papaya': 'Eyipapaali',
    'Yellow banana': 'Amenvu',
    'Bananas': 'Amatooke',
    'Plantain': 'Gonja',
    'Mango': 'Omuyembe',
    'introduction': 'Oliweyandhula',
    'Introduce yourself': 'Weyandhule',
    'Try': 'Gezaako',
    'I am': 'Ninze',
    'You': 'I whe',
    'He/She': 'Ole',
    'My name': 'Amaina Gange',
    'or': 'Oba',
    'They call': 'Amayina gange',
    'gender': 'Obutande',
    'Woman':'Mukazi',
    'Girl': 'Muwala',
    'Man':'Musanda',
    'Boy': 'Mulenzi',
    'no problem': 'Wazila Buzibo',
    'God':'katonda',
    'My man':'Musadha Wange',
    'My child': 'Mwana wange',
    'my boy': 'Mulenzi wange',
    'good': 'Mulungi',
    'young':'muto',
    'I am done': 'Mazze',
    'Yes':'Yiii',
    'no': 'Mbe',
    'water': 'Amadhi',
    'We are done': 'Tu Mazze',
    'today': 'Leero',
    'Amen': 'Amina',
    'Praise God':'mukama yebazibwe',
    'I am studying': 'Ndi Kusoma',
    'eating': 'Kulya',
    'How': 'Otya',
    'There':'Eyo',
    'How did you spend the night': 'Wasuze otya (eyo)',
    'Well':'Bulungi',
    'Madam': '(i)nhabo',
    'Thank you':'Weebale',
    'You also':'Weena',
    'Work': 'Emirimo',
    'I am excited to see you': 'Nsangaire okukubona',
    'May I come in?':'Koodi',
    'Come in':'Kalibu',
    'Welcome home':'Isuukayo',
    'I have returned':'Nviireyo',
    'I greet you ': 'Mbalamwisa',
    'How are you?': 'Oli otya (eyo)?',
    'What do you say?': 'Okoba ki?',
    'What\'s up friend?': 'Ki muna!',
    'Greet them!': 'Balamuse!',
    'Good bye':'Ale',
    'soon': 'Tubonagane',
    'The people at home': 'Ab\'eka',
    'They are': 'Bali',
    'Home': 'Eka',
    'what':'eki',
    'People': 'Abantu',
    'Any news?':'Amawulire ki?',
    'Food':'Emere',
    'jackfruit': 'Fene',
    
    
}
